# -*- coding: utf-8 -*-
"""
@Time    : 12/22/2020 9:00 PM
@Author  : yuanlixiang
@description: line直线
"""
from odoo import models, fields, api


class Siken_Data(models.Model):
    _name = 'siken.data'
    _description = 'Siken Data'

    bodyno = fields.Char(string='bodyno')
    koma = fields.Char(string='最后实验格子NO')
    pilc = fields.Char(string='格式')
    sikenday = fields.Date(string='实验日')
    kaisuu = fields.Char(string='测试次数')
    yobi1 = fields.Char(string='Jig No.')
    ondo = fields.Float(string='溫度')
    situdo = fields.Float(string='湿度')
    kiatu = fields.Float(string='气压')
    sdata00 = fields.Float(string='主数据-100%~0')
    sdata01 = fields.Float(string='主数据-50%~25')
    sdata02 = fields.Float(string='主数据0~50')
    sdata03 = fields.Float(string='主数据50%~75')
    sdata04 = fields.Float(string='T1采样数据100%~100')
    sdata05 = fields.Integer(string='T1采样数据-100%~0')
    sdata06 = fields.Integer(string='T1采样数据-50%~25')
    sdata07 = fields.Integer(string='T1采样数据0%~50')
    sdata08 = fields.Integer(string='T1采样数据50%~75')
    sdata09 = fields.Integer(string='T1采样数据100%~100')
    sdata10 = fields.Integer(string='T2采样数据-100%~0')
    sdata11 = fields.Integer(string='T2采样数据-50%~25')
    sdata12 = fields.Integer(string='T2采样数据0%~50')
    sdata13 = fields.Integer(string='T2采样数据5%~75')
    sdata14 = fields.Integer(string='T2采样数据100%~100')
    sdata15 = fields.Integer(string='T3测量数据-100%~0')
    sdata16 = fields.Integer(string='T4测量数据-100%~0')
    sdata17 = fields.Float(string='LKA')
    sdata18 = fields.Float(string='K')
    sdata19 = fields.Float(string='PV A/D(Zero)')
    sdata20 = fields.Integer(string='PV A/D(Span)')
    sdata21 = fields.Float(string='MV A/D(Zero)')
    sdata22 = fields.Float(string='MV A/D(Span)')
    sdata23 = fields.Integer(string='')
    sdata24 = fields.Float(string='')
    sdata25 = fields.Integer(string='')
    sdata26 = fields.Integer(string='')
    sdata27 = fields.Integer(string='')
    sdata28 = fields.Integer(string='')
    sdata29 = fields.Integer(string='')
    sdata30 = fields.Integer(string='')
    sdata31 = fields.Integer(string='')
    sdata32 = fields.Integer(string='')
    sdata33 = fields.Integer(string='')
    sdata34 = fields.Integer(string='')
    sdata35 = fields.Float(string='')
    sdata36 = fields.Float(string='')
    sdata37 = fields.Float(string='')
    sdata38 = fields.Float(string='')
    sdata39 = fields.Float(string='')
    sdata40 = fields.Float(string='')
    sdata41 = fields.Float(string='')
    sdata42 = fields.Float(string='')
    sdata43 = fields.Float(string='')
    sdata44 = fields.Float(string='')
    sdata45 = fields.Float(string='')
    sdata46 = fields.Float(string='')
    sdata47 = fields.Float(string='')
    sdata48 = fields.Float(string='')
    sdata49 = fields.Float(string='')
    sdata50 = fields.Float(string='')
    sdata51 = fields.Float(string='')
    sdata52 = fields.Float(string='')
    sdata53 = fields.Float(string='')
    sdata54 = fields.Float(string='')
    sdata55 = fields.Float(string='')
    sdata56 = fields.Float(string='')
    sdata57 = fields.Float(string='')
    sdata58 = fields.Float(string='')
    sdata59 = fields.Float(string='')
    sdata60 = fields.Float(string='')
    sdata61 = fields.Float(string='')
    sdata62 = fields.Float(string='')
    sdata63 = fields.Float(string='')
    sdata64 = fields.Float(string='')
    sdata65 = fields.Selection([('1', 'Good'),
                                ('2', 'Ng(Zero)'),
                                ('3', 'Ng(Span)'),
                                ('4', 'Ng(All)')
                                ], string='结果')
    sdata66 = fields.Float(string='')
    sdata67 = fields.Integer(string='')
    sdata68 = fields.Float(string='')
    sdata69 = fields.Integer(string='LKA错误标志')
    sdata70 = fields.Integer(string='K错误标志')
    sdata71 = fields.Integer(string='')
    sdata72 = fields.Integer(string='')
    sdata73 = fields.Integer(string='')
    sdata74 = fields.Integer(string='')
    sdata75 = fields.Integer(string='')
    sdata76 = fields.Integer(string='')
    sdata77 = fields.Integer(string='')
    sdata78 = fields.Integer(string='')
    sdata79 = fields.Integer(string='')
    sdata80 = fields.Integer(string='')
    yobi2 = fields.Char(string='备用')
    udf = fields.Integer()
    lineno = fields.Char()
